### ISSUE TITLE
Required parameter 'p' is missing

### ISSUE THREAD

**Issue by gsantner** [arubislander/uSonic#8]
Hello! I wanted to give this a shot, but sadly I cannot login with it (but can on both Android apps).

Below is the message and the version.

![screenshot20191127_021539330](https://user-images.githubusercontent.com/6735650/69685478-6a316080-10b4-11ea-81e2-0248ab57491a.png)
![screenshot20191127_021720742](https://user-images.githubusercontent.com/6735650/69685480-6b628d80-10b4-11ea-8e0b-ef3382b1b307.png)

I'm using https://github.com/spl0k/supysonic as subsonic server since some time, as the other forks of forks of forks didn't work well.

Subsonic API  (<http://www.subsonic.org/pages/api.jsp>) lists either p or t+s. I guess in usonic case t+s is set which doesn't work with that server. Can you add a checkbox option to switch over to p instead of t+s, at the login page?

**Comment by arubislander** [comment]
Hi,

Thanks for your interest in uSonic. I am sorry it doesn't work with the
server software of your choice.

I think I understand what the issue is. Apart from your proposed solution
another option would be for the app to check and see what version of the
Subsonic API the server is using and react accordingly.

I cannot promise I will be looking into it in the short term as my time is
being taken up with lots of personal matters at the moment. But it is
definitely on the radar now.

Greetings,
Terence

**Comment by gsantner** [comment]
Thanks!

As said,a simple toggle would be enough that switchtes the auth method (guess also the easiest to implement)

**Comment by arubislander** [comment]
You would think so, but actually reacting to the version the server reports
is easier, since it would not require having to implement the toggle ui
element and the code needed to store and read it's value. The code to
actually send the u+p combination would be the same either way.

**Comment by gsantner** [comment]
What value / API call do I need to get you required information?

**Comment by gsantner** [comment]
```
curl https://supysonichost/subsonic/rest/ping

<?xml version="1.0" ?>
<subsonic-response status="failed" version="1.9.0" xmlns="http://subsonic.org/restapi">
  <error code="10" message="Required parameter 'u' is missing."/>
</subsonic-response>
```

does that help? Version 1.9.0

![grafik](https://user-images.githubusercontent.com/6735650/70268223-ea805180-1797-11ea-8978-15f915733d5a.png)
![grafik](https://user-images.githubusercontent.com/6735650/70268186-d5a3be00-1797-11ea-9e2c-7b9b167aac98.png)

**Comment by arubislander** [comment]
I appreciate your eagerness. Thank you also for the information. Yes. The
xml you shared tells me the API version is 1.9.0. That confirms what we had
come to assume.
I cannot give any promises, but I will see if I can do a fix this weekend.

Thanks again for reaching out.

**Comment by gsantner** [comment]
I've worked on a subsonic client on my own, which works both ways. Anyway dont use this one, so feel free to close if you are not interested.
